name: Publish package to the Maven Central Repository

on:
  push:
    tags: [ "*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Guess Dependency Declaration Version
        run: |
          cd .github
          javac ReadmeUpdater.java
          java ReadmeUpdater ${{github.ref_name}}
      - name: Propose a PR to Update Readme
        uses: peter-evans/create-pull-request@v3
        with:
          base: main
          author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit-message: "chore: add license header(s)"
          title: "chore: update maven and gradle dependency declarations"
          body: Update version info in dependency declarations to `${{github.ref_name}}`.
          branch: readme-dep-ver
          
