name: Publish package to the Maven Central Repository

on:
  push:
    tags: [ "*" ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Guess Dependency Declaration Version
        run: |
          cd .github
          javac ReadmeUpdater.java
          java ReadmeUpdater ${{github.ref_name}}
